### PR TITLE
lib/storage: fix `searchTenantsOnDate` returns wrong tenants map

### LINKED ISSUE #10295: `admin/tenants?start=xxx&end=xxx` will include tenants with empty time series in this time period
### Is your question related to a specific component?

I think it releated with vmstorage.

### Describe the question in detail

As the title asked, was this by design? Is it possible to obtain a list of tenants with time series within a specified time period?

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/victoriametrics/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/victoriametrics/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/victoriametrics/vmalert/#troubleshooting

### PR DESCRIPTION
**Pull request by Defined2014**
### Describe Your Changes

fix #10295 

The `searchTenantsOnDate` function currently returns a map containing all tenants, rather than only those that have metrics on the specified date.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres to [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/victoriametrics/contributing/#pull-request-checklist).
- [x] My change adheres to [VictoriaMetrics development goals](https://docs.victoriametrics.com/victoriametrics/goals/).

### CODE REVIEW

**Comment by Defined2014** [comment]
@makasim @f41gh7 Would you take a look at this PR？ Thanks a lot.

**Comment by jiekun** [comment]
Thank you for your pull request. We process issues and pull requests in the order they are received, so please refrain from pinging our maintainers unless there has been an unusually long delay in our response.

**Comment by makasim** [comment]
Thank you for the PR, could you please add a changelog for it ?

**Comment by Defined2014** [comment]
> Thank you for the PR, could you please add a changelog for it ?

Done, but I'm not sure if the position is correct.

File: lib/storage/index_db_test.go [hunk 1]
```diff
@@ -2262,3 +2262,99 @@ func TestSearchLabelValues(t *testing.T) {
 	s.MustClose()
 	fs.MustRemoveDir(path)
 }
+
+func TestSearchTenantsOnDate(t *testing.T) {
```
Comment (rtm0) [inline lib/storage/index_db_test.go]: Please move the test to the Storage level instead of testing at the idb/is level.  See other tests in storage_test.go Let me know if you need help with this.

Comment (Defined2014) [reply lib/storage/index_db_test.go]: Done

File: lib/storage/storage_test.go [hunk 2]
```diff
@@ -973,6 +973,58 @@ func TestStorageDeleteSeries_TooManyTimeseries(t *testing.T) {
...
+	path := t.Name()
+	s := MustOpenStorage(path, OpenOptions{})
+	defer s.MustClose()
+
+	base := time.Now().UTC().Truncate(24*time.Hour).UnixMilli() - 4*24*time.Hour.Milliseconds() // 4 days ago
+	date1Start := base
+	date2Start := base + msecPerDay
+	date3Start := base + 2*msecPerDay
+
+	tr1 := TimeRange{MinTimestamp: date1Start, MaxTimestamp: date1Start + msecPerDay}
```
Comment (rtm0) [inline lib/storage/storage_test.go]: Subtract 1 millisecond from the MaxTimestamp. Currently it captures the next day. Since metrics are generated randomly, some of them may end up at MaxTimestamp at times which make tests fail and as a result will make them flaky.

Comment (Defined2014) [reply lib/storage/storage_test.go]: Done

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by f41gh7** [comment]
Bugfix was back-ported to the v1.122 and v1.110 LTS branches
