### PR TITLE
lib/streamaggr: fixed streamaggr panic

### LINKED ISSUE #8469: vmagent got panic: runtime error: invalid memory address or nil pointer dereference
### Describe the bug

Our victoria-metrics-agent pod got CrashLoopBackOff because of `panic: runtime error: invalid memory address or nil pointer dereference` as below on one cluster. There was maxScrapeSize message before the panic.
From the panic log, seems something related to streamaggr handlling. We have streaming aggregation configured and the streaming aggregation is working good on this cluster while it was Running before hitting the CrashLoopBackOff, and working good on other clusters.

```
{"ts":"2025-03-10T01:20:46.354Z","level":"warn","caller":"VictoriaMetrics/lib/promscrape/scrapework.go:383","msg":"cannot scrape target \"http://1.3.19.13:8080/metrics\" ({instance=\"1.3.19.13:8080\",job=\"kube-state-metrics\"}) 1 out of 1 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: the response from \"http://1.3.19.13:8080/metrics\" exceeds -promscrape.maxScrapeSize or max_scrape_size in the scrape config (40000000 bytes). Possible solutions are: reduce the response size for the target, increase -promscrape.maxScrapeSize command-line flag, increase max_scrape_size value in scrape config for the given target"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x835e2f]

goroutine 6 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.putRateAggrStateValue(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/rate.go:32
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*rateAggrSharedValue).reset(0xc00157ba70)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/rate.go:74 +0x4f
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.putRateAggrSharedValue(0xc00157ba70)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/rate.go:11 +0x18
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*rateAggrValue).flush(0xc00115f780, {0xcc9820?, 0xc0001a8968}, 0xc00b180ee0, {0xc0015d2a40, 0x9})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/rate.go:126 +0x225
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggrOutputs).flushState.func1({0xa64740, 0xc00115f790}, {0xa504a0?, 0xc002515a40})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/output.go:115 +0x209
sync.(*Map).Range(0xc006974d50?, 0xc006974d50)
        sync/map.go:501 +0x1f8
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggrOutputs).flushState(0xc000238fc0?, 0xc000298c80?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/output.go:94 +0x4e
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggregator).flush(0xc000238fc0, 0xc21fb0, {0x128bf40?, 0x2e7ddb00?, 0x128bf40?}, 0xc0012548d0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:935 +0x145
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.(*aggregator).runFlusher(0x0?, 0xc21fb0, 0x0, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:852 +0x587
github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.newAggregator.func3()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:712 +0x2c
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr.newAggregator in goroutine 1
        github.com/VictoriaMetrics/VictoriaMetrics/lib/streamaggr/streamaggr.go:711 +0x26c5
```

### To Reproduce

described above. vmagent version: 1.112.0.

### Version

vmagent version: 1.112.0

### Logs

_No response_

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### Describe Your Changes

fixes #8469

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by jiekun** [comment]
Thanks for the quick fix! 

Some question but maybe not related to the fix impl in this PR:
- previously when checking why `v` could be `nil`, it seems it's accessed by multiple goroutine, is it expected or safe? Didn't have chance to trace further but is it because `shared  map[string]*rateAggrSharedValue` pointing to same value bla bla bla?

It's for understand the reason of 'in where these value are accessed by goroutines'. If we need to avoid these cases, perhaps we also need to fix them there Otherwise, the current fixes seem to be sufficient to prevent panic.

**Comment by AndrewChubatiuk** [comment]
nil is possible there while aggregation windows are disabled as `green` state is not initialized

**Review by jiekun — APPROVED** [review]
Thanks for the explanation! If it's not caused by concurrent access, this fix should be sufficient.

File: lib/streamaggr/rate.go [hunk 1]
```diff
@@ -29,6 +29,9 @@ func getRateAggrSharedValue(isGreen bool) *rateAggrSharedValue {
 var rateAggrStateValuePool sync.Pool
 
 func putRateAggrStateValue(v *rateAggrStateValue) {
+	if v == nil {
```
Comment (hagen1778) [inline lib/streamaggr/rate.go:32]: @AndrewChubatiuk can we add a test case that could have caught this?
I know that test stream aggregation is not an easy, however if not checking the correctness of the output  we still can verify races and issues like this with unittests.

Comment (AndrewChubatiuk) [reply lib/streamaggr/rate.go]: updated method, so now this error reproducible in tests

**Review by hagen1778 — APPROVED** [review]
LGTM
