### PR TITLE
fix CounterMap performance with large numbers of tenants

### LINKED ISSUE #7482: vminsert performance issue restarting process with large number of tenants
### Describe the bug

When the number of tenants sending data through `vminsert` grows large, a performance issue occurs when restarting the `vminsert` process that significantly impairs ingestion for several minutes.

I tracked down the issue to a quadratic algorithm in the implementation of `CounterMap` that causes a CPU bottleneck as the in-memory map for the `vm_tenant_inserted_rows_total` metric counters gets populated with tenant keys.

### To Reproduce

High-level steps to reproduce the issue in a production setup:
* Send metrics through vminsert across a large number of tenants (`n` > 10,000 in my use-case)
* Restart the vminsert process under constant load
* Observe performance degradation for a number of minutes as the tenant map gets populated.

The following benchmark reproduces the performance issue in `CounterMap` more narrowly:

```
func BenchmarkCounterMapGrowth(b *testing.B) {
        const n = 10_000
	for i := 0; i < b.N; i++ {
		cm := NewCounterMap("foobar")
		for i := uint32(0); i < n; i++ {
			cm.Get(&auth.Token{AccountID: i}).Inc()
		}
	}
}
```

This runs ~300x faster using a `sync.Map` implementation, when `n` = 10,000.

### Version

`vminsert-20241104-145042-tags-v1.106.0-cluster-0-g48d3052901` in production, but I believe this performance issue is present in any version of `vminsert` since 8cf0a0e59c7958e3bcf4d708a4004d14e7e36cb3.

### Logs

A [CPU profile](https://github.com/user-attachments/files/17667175/profile001.pdf) first pointed me to map assignments in `(*CounterMap) GetByTenant` as the source of the performance issue:
image

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wjordan**
### Describe Your Changes

Use `sync.Map` for the implementation of `CounterMap`, instead of re-creating a new Map when each new tenant is added.

Fixes #7482.

In order to validate that this change doesn't cause any performance regression, I've added a benchmark test `BenchmarkCounterMapGrowth` that demonstrates the performance improvement across a range of values of `n` (100, 1000, 10,000) across 2 goroutines (which matched my own use-case), and also across GOMAXPROCS goroutines (to ensure that concurrent performance isn't negatively impacted).

These are the results on my local machine:
```
goos: linux
goarch: amd64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/tenantmetrics
cpu: AMD Ryzen 9 5900X 12-Core Processor            
                                            │ lib/tenantmetrics/orig.bench │     lib/tenantmetrics/new.bench     │
                                            │            sec/op            │    sec/op     vs base               │
CounterMapGrowth/n=100,nProcs=GOMAXPROCS-24                  1943.2µ ±  5%   248.0µ ± 11%  -87.24% (p=0.001 n=7)
CounterMapGrowth/n=100-24                                    434.63µ ±  5%   98.82µ ± 16%  -77.26% (p=0.001 n=7)
CounterMapGrowth/n=1000-24                                   32.719m ± 20%   1.425m ±  5%  -95.65% (p=0.001 n=7)
CounterMapGrowth/n=10000-24                                 3653.60m ±  5%   18.00m ±  2%  -99.51% (p=0.001 n=7)
geomean                                                       17.83m         890.4µ        -95.00%
```

Please feel free to edit/update the benchmark however it may be useful for CI.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

File: lib/tenantmetrics/counter_map_test.go [hunk 1]
```diff
@@ -88,3 +90,34 @@ func TestCounterMapConcurrent(t *testing.T) {
...
+		{name: "n=100", n: 100, nProcs: 2},
+		{name: "n=1000", n: 1000, nProcs: 2},
+		{name: "n=10000", n: 10000, nProcs: 2},
+	}
+
+	for _, bm := range benchmarks {
+		b.Run(bm.name, func(b *testing.B) {
+			for i := 0; i < b.N; i++ {
+				cm := NewCounterMap("foobar")
+				eg := errgroup.Group{}
```
Comment (rtm0) [inline lib/tenantmetrics/counter_map_test.go:110]: Why not just use WaitGroup? The goroutines do not seem to return errors.

File: lib/tenantmetrics/counter_map_test.go [hunk 2]
```diff
@@ -88,3 +90,34 @@ func TestCounterMapConcurrent(t *testing.T) {
 		t.Fatalf("unexpected counter value; got %d; want %d", n, concurrency*10*5)
 	}
 }
+
+func BenchmarkCounterMapGrowth(b *testing.B) {
```
Comment (rtm0) [inline lib/tenantmetrics/counter_map_test.go:94]: Please move the benchmark to the counter_map_timing_test.go (it does not exist yet, you'd need to create it). This is a convention we use: benchmarks are placed into _timing_test.go files.

Comment (rtm0) [reply lib/tenantmetrics/counter_map_test.go:94]: Also, we've been using so called f-tests instead of table-driven tests. See: https://itnext.io/f-tests-as-a-replacement-for-table-driven-tests-in-go-8814a8b19e9e

May I ask to you to re-structure the test in order to adhere to our coding style? It should be something like this:

```go
func BenchmarkCounterMapGrowth(b *testing.B) {
        f := func(b *testing.B, n uint32, nProcs int) {
                b.Helper()

                for i := 0; i < b.N; i++ {
                        cm := NewCounterMap("foobar")
                        var wg sync.WaitGroup
                        for range nProcs {
                                wg.Add(1)
                                go func() {
                                        for i := range numTenants {
                                                cm.Get(&auth.Token{AccountID: i, ProjectID: i}).Inc()
                                        }
                                        wg.Done()
                                }()
                        }
                        wg.Wait()
                }
        }

        b.Run("n=100,nProcs=GOMAXPROCS", func(b *testing) {
                f(b, 100, runtime.GOMAXPROCS(0))
        })

        b.Run("n=100,nProcs=2", func(b *testing) {
                f(b, 100, 2)
        })

        b.Run("n=1000,nProcs=2", func(b *testing) {
                f(b, 1000, 2)
        })

        b.Run("n=10000,nProcs=2", func(b *testing) {
                f(b, 10000, 2)
        })
}
```

**Review by rtm0 — CHANGES_REQUESTED** [review]
Hi @wjordan, the fix looks good. Just a few remarks regarding the benckmark.

**Review by rtm0 — APPROVED** [review]

**Comment by f41gh7** [comment]
Thanks for contribution!
