### PR TITLE
app/vlinsert: better error reporting in the /jsonline handler

### LINKED ISSUE #8818: VictoriaLogs: better error reporting for /insert/jsonline
### Describe the bug

When I send invalid JSON to `/insert/jsonline`, VictoriaLogs writes an error to the log, but returns status 200.

### To Reproduce

```
 echo { | curl -vv -X POST -H 'Content-Type: application/stream+json' --data-binary @- 'http://localhost:9428/insert/jsonline'
```

I would expect an error in the 4xx range (probably 400).

### Version

victoria-logs-v1.18.0

### Logs

_No response_

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vadimalekseev**
### Describe Your Changes

This pull request improves error messages in the /jsonline handler by returning a 400 Bad Request if no logs were processed.

Closes #8818

Example requests-response:
```sh
$ curl -X POST -H 'Content-Type: application/jsonl' http://localhost:9428/insert/jsonline -d '{"_time":"foobar"}'
remoteAddr: "127.0.0.1:50439"; requestURI: /insert/jsonline; cannot process jsonline request; error: cannot parse timestamp from field "_time": cannot parse unix timestamp from "foobar": strconv.ParseInt: parsing "foobar": invalid syntax; line contents: "{\"_time\":\"foobar\"}"

$ curl -X POST -H 'Content-Type: application/jsonl' http://localhost:9428/insert/jsonline -d 'foo'
remoteAddr: "127.0.0.1:50413"; requestURI: /insert/jsonline; cannot process jsonline request; error: cannot parse JSON: unexpected value found: "foo"; unparsed tail: "foo"; line contents: "foo"
```

### Checklist

The following checks are **mandatory**:

- [X] My change adheres to [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

File: app/vlinsert/jsonline/jsonline.go [hunk 1]
```diff
@@ -89,7 +104,7 @@ func readLine(lr *insertutil.LineReader, timeField string, msgFields []string, l
 	defer logstorage.PutJSONParser(p)
 
 	if err := p.ParseLogMessage(line); err != nil {
-		return true, fmt.Errorf("cannot parse json-encoded line: %w; line contents: %q", err, line)
```
Comment (vadimalekseev) [inline app/vlinsert/jsonline/jsonline.go:92]: This change is needed to avoid duplicating error messages like:
`cannot parse json-encoded line: cannot parse json: cannot parse JSON ...`

File: lib/logstorage/json_parser.go [hunk 2]
```diff
@@ -78,7 +77,7 @@ func (p *JSONParser) parseLogMessage(msg []byte, maxFieldNameLen int) error {
 	msgStr := bytesutil.ToUnsafeString(msg)
 	v, err := p.p.Parse(msgStr)
 	if err != nil {
-		return fmt.Errorf("cannot parse json: %w", err)
```
Comment (vadimalekseev) [inline lib/logstorage/json_parser.go:81]: This change is needed to avoid duplicating error messages like:
`cannot parse json: cannot parse JSON ...`

File: app/vlinsert/jsonline/jsonline.go [hunk 3]
```diff
@@ -89,11 +104,11 @@ func readLine(lr *insertutil.LineReader, timeField string, msgFields []string, l
...
+		return true, fmt.Errorf("%s; line contents: %q", err, line)
 	}
 	ts, err := insertutil.ExtractTimestampFromFields(timeField, p.Fields)
 	if err != nil {
-		return true, fmt.Errorf("cannot get timestamp from json-encoded line: %w; line contents: %q", err, line)
```
Comment (vadimalekseev) [inline app/vlinsert/jsonline/jsonline.go:96]: This change is needed to avoid duplicating error messages like:
`cannot get timestamp from json-encoded line: cannot parse timestamp from field "_time": cannot parse unix timestamp from "foobar"`

**Review by valyala — APPROVED** [review]
Looks good!

The final logic of processStreamInternal() should be the following:

1. If some JSON lines at `r` were successfully parsed, then the function shouldn't return any errors, and the client shouldn't receive any errors, since this is the expected case.
2. If all the JSON lines at `r` were invalid, then the error should be returned to the client in order to improve the debuggability of this case.

All the parse errors must be logged by VictoriaLogs with the WARN level.

File: app/vlinsert/jsonline/jsonline_test.go [hunk 4]
```diff
@@ -44,22 +47,6 @@ func TestProcessStreamInternal(t *testing.T) {
 {"message":"baz"}`
 	f(data, timeField, msgField, timestampsExpected, resultExpected)
 
-	// invalid json
```
[the remark this answers is not in the document]
Comment (vadimalekseev) [reply app/vlinsert/jsonline/jsonline_test.go:47]: If I'm not mistaken, such a test case already exists with the comment `// invalid lines among valid lines`. Correct me if I'm wrong.

**Comment by vadimalekseev** [comment]
@valyala, as a follow-up task, please take a look at the option suggested here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8818#issuecomment-2838084130.  
Should we also support error reporting in the `/insert/elasticsearch/_bulk` handler?

**Review by f41gh7 — APPROVED** [review]
LGTM

Could you please mention changes at `docs/victorialogs/CHANGELOG.md`?

**Comment by f41gh7** [comment]
Btw, this error will NOT be reported back to the client, if server already ack-ed a part of the stream request and replied with `200` status code.

**Comment by f41gh7** [comment]
> > 
> 
> I don't get this. If I understand correctly, the current logic is to parse all the logs in the request in streaming manner (e.g. one-by-one) and immediately store the parsed logs without buffering them in RAM or at disk until the end of request. Then return the response status code after all the logs in the request body are parsed. This allows ingesting arbitrary long request body into VictoriaLogs, without worrying on RAM usage and/or disk space usage.

 Yes, I was wrong and I had an assumption, that victoria-logs http server performs some flushes with response back to the client. I made a comment at the related issue. 

 So, this PR will work as expected for any size of streaming workload.
