### PR TITLE
vmui: always add /prometheus prefix while generating backend url

### LINKED ISSUE #10097: vmui: guesses wrong urls when using target_path_suffix
### Describe the bug

Hi,

i have a VMCluster along with VMAuth and VMUser. And the VMUser uses target_path_suffix to just expose tenant 0 for that user.

Since v1.125.0 vmui is broken, it tries to access /api/v1/status instead of /prometheus/api/v1/status

### To Reproduce

Create a user like this:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: {{ $u }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/component: vmuser
spec:
  username: testuser
  password: testpass
  targetRefs:
  - crd:
      kind: VMCluster/vmselect
      name: cluster
      namespace: {{ $.Values.namespace }}
    target_path_suffix: /select/0
    paths:
    - /prometheus/api/v1/export
    - /prometheus/api/v1/export/native
    - /prometheus/api/v1/labels
    - /prometheus/api/v1/label/.*/values
    - /prometheus/api/v1/query
    - /prometheus/api/v1/query_range
    - /prometheus/api/v1/series
    - /prometheus/api/v1/status/.*
    - /prometheus/federate
    - /prometheus/vmui/.*
    - /api/v1/status/.*
    - /vmui
    - /vmui/.*
```

Point browser to https://vmauth/vmui/ and login with testuser:testpass. Try querying something or open cardinality explorer. It works before v1.125.0 and stops working with v1.125.0 and later.

### Version

k exec vmselect-cluster-0 -- ./vmselect-prod --version
vmselect-20251117-143437-tags-v1.130.0-cluster-0-ge7d9e1dbc3

### Logs

before v1.125.0:

Image

after v1.125.0:

Image

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
fixes #10097 

always add /prometheus prefix while generating backend url

### Describe Your Changes

Please provide a brief description of the changes you made. Be as specific as possible to help others understand the purpose and impact of your modifications.

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres to [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/victoriametrics/contributing/#pull-request-checklist).
- [ ] My change adheres to [VictoriaMetrics development goals](https://docs.victoriametrics.com/victoriametrics/goals/).

### CODE REVIEW

File: app/vmui/packages/vmui/src/state/common/reducer.ts [hunk 1]
```diff
@@ -56,7 +56,8 @@ export function reducer(state: AppState, action: Action): AppState {
     case "SET_APP_CONFIG":
       return {
         ...state,
-        appConfig: action.payload
+        appConfig: action.payload,
+        serverUrl: state.serverUrl || getDefaultServer(!!action.payload.isCluster, tenantId),
```
Comment (Loori-R) [inline app/vmui/packages/vmui/src/state/common/reducer.ts]: This uses `tenantId` from the initial query string. If `tenantId` can change via `SET_TENANT_ID`, use `state.tenantId` here to avoid stale values.

File: app/vmui/packages/vmui/src/utils/default-server-url.ts [hunk 2]
```diff
@@ -3,15 +3,16 @@ import { replaceTenantId } from "./tenants";
 import { APP_TYPE, AppType } from "../constants/appType";
 import { getFromStorage } from "./storage";
 
-export const getDefaultURL = (u: string) => {
-  return u.replace(/(\/(?:prometheus\/)?(?:graph|vmui)\/.*|\/#\/.*)/, "").replace(/(\/select\/[^/]+)$/, "$1/prometheus");
+export const getDefaultURL = (u: string, isCluster: boolean) => {
+  const replacement = isCluster ? "/prometheus" : "";
+  return u.replace(/(\/(?:prometheus\/)?(?:graph|vmui)\/.*|\/#\/.*)/, replacement);
 };
```
Comment (Loori-R) [inline app/vmui/packages/vmui/src/utils/default-server-url.ts:8]: Is it expected that in cluster mode we never get `https://host/select/<tenant>` without `/prometheus`?

Example:

* Before: `https://host/select/<tenant>` → `https://host/select/<tenant>/prometheus`
* Now:  `https://host/select/<tenant>` → `https://host/select/<tenant>`

File: app/vmui/packages/vmui/public/config.json [hunk 3]
```diff
@@ -1,5 +1,6 @@
 {
   "license": {
     "type": "opensource"
-  }
+  },
+  "isCluster": false
```
Comment (makasim) [inline app/vmui/packages/vmui/public/config.json]: To myself: Has to be changed to `true` in the cluster branch on merge

**Comment by AndrewChubatiuk** [comment]
@makasim @Loori-R 
instead of introducing `isCluster` variable just restored previous behaviour since VMUI path is not static and in cluster setups /prometheus prefix should be added only if `vmui` is not already mounted into `/prometheus`, which could make url generation logic even more complex

**Review by makasim — APPROVED** [review]

**Comment by makasim** [comment]
The bug fix was merged to the latest and ported to LTS v1.122.x line.
