### PR TITLE
lib/storage: shard metricIdCache

### LINKED ISSUE #10367: lib/storage: Data ingestion lock contention in versions v1.133.0+
### Describe the bug

After upgrading to v1.133.0+ (introduces the `partition index`, see #7599 and #8134) users observe increased CPU context switches and periodic increases in connection saturation between vminsert and vmstorage.

Image

### To Reproduce

- Bring up an open source cluster
- There should be more than one vminsert
- Ingest rows and observe the `Connection saturation` chart in the vmisert section. There thould be a spike every 10 minutes.

### Version

vmstorage v1.133.0+

### PR DESCRIPTION
**Pull request by tIGO**
### Describe Your Changes

The current implementation has a bottleneck – a single mutex to access `prev`/`next` metric sets. Each rotation results in storage utilization spikes since lock-free `curr` is almost empty, and cache needs to promote metrics from `prev` to `next`.

This is an attempt to reduce contention by spliting cache into separate shards.

Fixes #10367.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres to [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/victoriametrics/contributing/#pull-request-checklist).
- [x] My change adheres to [VictoriaMetrics development goals](https://docs.victoriametrics.com/victoriametrics/goals/).

### CODE REVIEW

File: lib/storage/metric_id_cache.go [hunk 1]
```diff
@@ -4,18 +4,124 @@ import (
...
+	stopCh            chan struct{}
+	rotationStoppedCh chan struct{}
+}
+
+func newMetricIDCache() *metricIDCache {
+	c := metricIDCache{
+		stopCh:            make(chan struct{}),
+		rotationStoppedCh: make(chan struct{}),
+	}
+	for i := 0; i < metricIDCacheShardNum; i++ {
```
Comment (f41gh7) [inline lib/storage/metric_id_cache.go]: WDYT of making shard count configurable? Like it implemented at blockcache:
```
	cpusCount := cgroup.AvailableCPUs()
	shardsCount := cgroup.AvailableCPUs()
	// Increase the number of shards with the increased number of available CPU cores.
	// This should reduce contention on per-shard mutexes.
	multiplier := cpusCount
	if multiplier > 16 {
		multiplier = 16
	}
	shardsCount *= multiplier
```

**Comment by rtm0** [comment]
[benchstat.txt](https://github.com/user-attachments/files/24940407/benchstat.txt)

File: lib/storage/metric_id_cache.go (hunk 1 above)
Comment (rtm0) [reply lib/storage/metric_id_cache.go]: Done. PTAL.

File: lib/storage/metric_id_cache.go [hunk 2]
```diff
@@ -13,9 +16,117 @@ import (
...
+}
+
+func (c *metricIDCache) Set(metricID uint64) {
+	shardIdx := fastHashUint64(metricID) % uint64(len(c.shards))
+	c.shards[shardIdx].Set(metricID)
+}
+
+func (c *metricIDCache) rotate(rotationGroup int) {
+	for i := range len(c.shards) {
+		if i/c.numRotationGroups == rotationGroup {
```
Comment (tIGO) [inline lib/storage/metric_id_cache.go]: Probably you want `%` here (previously group size was used, not group count)

Comment (rtm0) [reply lib/storage/metric_id_cache.go]: Fixed. PTAL

**Comment by rtm0** [comment]
[benchstat2.txt](https://github.com/user-attachments/files/24944947/benchstat2.txt) - the benchmark shows that is slower and occupies much more space.

However, test deployment results are not that dramatic:

- CPU increases by 10%:

Screenshot_20260129_185805

- Memory stays the same. Periodic peaks in vminsert are gone because there is no connection saturation spikes anymore:

Screenshot_20260129_190059

- Storage connection saturation spikes are gone:

Screenshot_20260129_190726

File: lib/storage/metric_id_cache.go [hunk 3]
```diff
@@ -13,9 +16,119 @@ import (
...
+		stats.Size += s.Size
+		stats.SizeBytes += s.SizeBytes
+		stats.SyncsCount += s.SyncsCount
+		stats.RotationsCount += s.RotationsCount
+	}
+	return stats
+}
+
+func (c *metricIDCache) Has(metricID uint64) bool {
+	shardIdx := fastHashUint64(metricID) % uint64(len(c.shards))
```
Comment (tIGO) [inline lib/storage/metric_id_cache.go:89]: Is it intentional not use `numShards()` here? I guess it'll be inlined anyway.

Comment (rtm0) [reply lib/storage/metric_id_cache.go:89]: In some places like this one it would make sense, other places rely on int value of len(). So I'd keep it as is for consistency. The method was introduced to be used in tests.

File: docs/victoriametrics/changelog/CHANGELOG.md [hunk 4]
```diff
@@ -78,6 +79,10 @@ Released at 2026-01-16
 Released at 2026-01-02
 
 **Update Note 1:** [vmsingle](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/) and `vmstorage` in [VictoriaMetrics cluster](https://docs.victoriametrics.com/victoriametrics/cluster-victoriametrics/): Upgrading to per-partition index requires registering all active time series. Expect slow down of data ingestion and queries during upgrade roll-out. This is a one-time operation. Additionally, for users with retention periods shorter than 1 month the disk usage may increase.
+**Update Note 2:** [vmsingle](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/) and `vmstorage` in [VictoriaMetrics cluster](https://docs.victoriametrics.com/victoriametrics/cluster-victoriametrics/): Running this version in deployments with big datasets may cause high CPU utilization. See [10297](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/10297).
```
[the remark this answers is not in the document]
Comment (rtm0) [reply docs/victoriametrics/changelog/CHANGELOG.md:82]: Update notes 2-5 are related to v1.133.0 and therefore placed under that version.

[the remark this answers is not in the document]
Comment (rtm0) [reply docs/victoriametrics/changelog/CHANGELOG.md:82]: Same here. Update notes 2-5 are related to v1.133.0 and therefore placed under that version.

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by makasim** [comment]
There is no need to backport the change to LTS lines as the bug was introduced in v1.133.0
