### PR TITLE
Utilize persisted `hourMetricIDs` cache to avoid redundant `indexDB` lookups after vmstorage restart

### LINKED ISSUE #10114: CPU spikes at the beginning of each hour after vmstorage restart
### Describe the bug

`updatePerDateData` doesn't account the `hourMetricIDs` cache rotation timing, which causes rows with adjacent-hour timestamps to fall through to the `dateMetricIDCache` cache.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1985c79a4d0386d9478dec76cc83fb825db93c7b/lib/storage/storage.go#L2347-L2384

After a restart, `dateMetricIDCache` cache is empty, resulting in redundant `indexDB` lookups.
Image

This causes CPU spikes and ingestion slowdown.
Image

Image

### To Reproduce

Restart vmstorage with high ingestion rate.

### Version

v1.128.0-cluster

### Logs

_No response_

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

The `updatePerDateData` function only checked `hour == hmCurr.hour` when deciding whether to use the hour cache. This missed two edge cases:
- **Rows with next-hour timestamps**: Cache rotation may lag behind the actual hour change. Rows arriving with `hour == hmCurr.hour + 1` bypass the cache entirely.
- **Rows with previous-hour timestamps**: Rows arriving just at the actual hour change may have timestamps from the previous hour, also bypassing the cache.

### PR DESCRIPTION
**Pull request by fxrlv**
### Describe Your Changes

fixes #10114

### Checklist

The following checks are **mandatory**:

- [x] My change adheres to [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/victoriametrics/contributing/#pull-request-checklist).
- [x] My change adheres to [VictoriaMetrics development goals](https://docs.victoriametrics.com/victoriametrics/goals/).

### CODE REVIEW

File: lib/storage/storage.go [hunk 1]
```diff
@@ -2371,6 +2375,13 @@ func (s *Storage) updatePerDateData(idb *indexDB, rows []rawRow, mrs []*MetricRo
 				// The metricID is already registered for the current day on the previous hour.
 				continue
 			}
+
+		case hmPrev.hour:
+			// Handle rows with timestamps from the previous hour.
+			// That is essential for rows arriving just at the actual hour change.
+			if hmPrev.m.Has(metricID) {
```
[the remark this answers is not in the document]
Comment (fxrlv) [reply lib/storage/storage.go]: this check would be redundant
the condition `hour == hmPrev.hour` implies that the dates are also equal

File: lib/storage/storage.go [hunk 2]
```diff
@@ -2344,9 +2345,12 @@ func (s *Storage) updatePerDateData(idb *indexDB, rows []rawRow, mrs []*MetricRo
 		}
 		prevDate = date
 		prevMetricID = metricID
-		if hour == hmCurr.hour {
+
```
Comment (rtm0) [inline lib/storage/storage.go]: Looks like this could be generalized to just using the sample timestamp date. Addionally, I next day prefill can be independent of current day checks.

```go
if hour == currentHour && pMin > 0 {
  // add to pendingNextDayMetricIDs
}

if date == hmCurrDate && hmCurr.m.Has(metricID) {
  continue
}

if date == hmPrevDate && hmPrev.m.Has(metricID) {
  continue
}

// Finally check in dmc.
```

I am not sure why adding next day metricIDs requires a metricIDs to be in currHourMetricIDs cache. I even added a unit test for this, but this does not mean it is a requirement. It looks like it is enough to just check which hour the sample timestamp corresponds.

Comment (fxrlv) [reply lib/storage/storage.go]: Given that, it definitely looks better. PTAL

**Comment by rtm0** [comment]
@fxrlv While we are fixing our CI, may I ask to try this change in your deployment and share the `after` charts? :)

**Comment by fxrlv** [comment]
Sure, applied the changes to instances 7–9 and restarted instances 4–9.
Although the ingestion rate is much lower than in the original issue, the difference is still noticeable.

Slow per-day index inserts
Screenshot 2025-12-10 at 12 07 11

CPU utilization (subset of instances with the same CPU model)
Screenshot 2025-12-10 at 12 07 52

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by f41gh7** [comment]
This PR cannot be ported to the LTS branches due to merge conflicts
