### PR TITLE
Azure Service Discovery - Fix token fetch for Container Apps/App Services

### LINKED ISSUE #3830: Azure SD Managed Identity auth doesn't work inside Azure Container Apps
### Describe the bug

When running VictoriaMetrics inside a [Azure Container App](https://learn.microsoft.com/en-us/azure/container-apps/overview) and using Azure service discovery with Managed Identity authentication method, I am unable to get a token.

### To Reproduce

Create a Container App and setup a VMAgent with Azure SD configuration and `ManagedIdentity` as auth method.
```
scrape_configs:
- job_name: test
  azure_sd_configs:
    - subscription_id: REDACTED
      authentication_method: 'ManagedIdentity'
  relabel_configs:
    - source_labels: [instance]
      regex: (.+)
      replacement: ${1}:1000
      target_label: __address__
```

Authentication will keep failing due to an empty token received. The actual result when using an older API version is either 401 or a response that older API versions doesn't work.
``

### Version

`vmagent-20230209-232200-tags-v1.87.1-0-g291c4197`

### Logs

`2023-02-16T16:58:04.476571186Z 2023-02-16T16:58:04.476Z error   VictoriaMetrics/lib/promscrape/config.go:1044   skipping azure_sd_config targets for job_name "test" because of error: cannot list virtual machines: cannot execute azure api request at /subscriptions/REDACTED/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01: unexpected status code returned from "https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01": 401; expecting 200; response body: "{\"error\":{\"code\":\"AuthenticationFailedMissingToken\",\"message\":\"Authentication failed. The 'Authorization' header is missing the access token.\"}}"`

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MattiasAng**
Fixes #3830.

While testing VMAgent inside [Azure Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/overview) together with Azure service discovery using Managed Identity I noticed I was not able to get a token from the [IMDS](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=windows) endpoint.

During investigation I noticed a few issues.
- The endpoint used in these resources requires a newer API version and a different auth header.
  - Solution I used is the same as [Azure Go SDK utilizes](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/managed_identity_client.go#L120) which is checking for the environment variable `IDENTITY_HEADER`, and adding the correct API version and header if it is set.
  - If using User Assigned Identity, the query parameter needs to be `client_id`.
- The token response from the endpoint only contains a `expires_on` in addition to the `access_token`.

### CODE REVIEW

File: lib/promscrape/discovery/azure/api.go [hunk 1]
```diff
@@ -235,15 +243,38 @@ func getRefreshTokenFunc(sdc *SDConfig, ac, proxyAC *promauth.Config, env *cloud
...
+// parseTokenExpiry returns token expiry in seconds
+func parseTokenExpiry(tr tokenResponse) (int64, error) {
+	var expiresInSeconds int64
+	var err error
+
+	if tr.ExpiresIn == "" {
+		var expiresOnSeconds int64
+		expiresOnSeconds, err = strconv.ParseInt(tr.ExpiresOn, 10, 64)
+		if err != nil {
+			return 0, fmt.Errorf("cannot parse token auth response %q: %w", tr.ExpiresOn, err)
```
Comment (valyala) [inline lib/promscrape/discovery/azure/api.go:265]:
```suggestion
			return 0, fmt.Errorf("cannot parse expiresOn=%q in auth token response: %w", tr.ExpiresOn, err)
```

File: lib/promscrape/discovery/azure/api.go [hunk 2]
```diff
@@ -235,15 +243,38 @@ func getRefreshTokenFunc(sdc *SDConfig, ac, proxyAC *promauth.Config, env *cloud
...
+		}
+		expiresInSeconds = expiresOnSeconds - time.Now().Unix()
+	} else {
+		expiresInSeconds, err = strconv.ParseInt(tr.ExpiresIn, 10, 64)
+		if err != nil {
+			return 0, fmt.Errorf("cannot parse token auth response %q: %w", tr.ExpiresIn, err)
```
Comment (valyala) [inline lib/promscrape/discovery/azure/api.go:271]:
```suggestion
			return 0, fmt.Errorf("cannot parse expiresIn=%q auth token response: %w", tr.ExpiresIn, err)
```

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@MattiasAng , thanks for the fix!
