### PR TITLE
app/vmselect: prom handler: LabelValues: decode UTF8-encoded label name

### LINKED ISSUE #10446: vmselect: Prometheus label values API is broken for Unicode label names (ie any label with a dot in it)
### Describe the bug

Querying the API is broken when I query label values for Unicode labels.

### To Reproduce

1. Have a metric with labels that contain dots in them (see the Screenshots section)
2. Query the prometheus label values API.
```
curl http://localhost:8481/select/0/prometheus/api/v1/label/U__k8s_2e_namespace_2e_name/values
```

Expected: a list of the labels
Got: 
```
{
  "status": "success",
  "isPartial": false,
  "data": []
}
```

Just to be sure, I queried other Unicode label names and they did not work too.

It works when I query non-unicode label names like `job` or `beta_kubernetes_io_instance_type`.

---

`curl http://localhost:8481/select/0/prometheus/api/v1/label/k8s.namespace.name/values` returns the label values, however, Grafana's `label_values` query sends the query according to the [Prometheus spec](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values) - which says that anything with dots should use the `U__` encoding.

### Version

victoriametrics/vmselect:v1.135.0-cluster
victoriametrics/vmstorage:v1.135.0-cluster

### Logs

_No response_

### Screenshots

http://localhost:8481/select/0/vmui/#/cardinality?topN=50&match=%7Bk8s.namespace.name%21%3D%22%22%7D&focusLabel=k8s.namespace.name : 
Image

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by utrack**
This MR is up for discussion; as @f41gh7 [mentioned](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/10446#issuecomment-3884314331), we may want to introduce a query parameter to specify the escape format.

I'm not sure if it's worth it because Grafana's Prometheus DS will stay silently broken by default, unless the `Custom query parameters` is set; doubly so because the Unicode-encoded names have a clear signature (the `U__` prefix).

The [decoding function itself](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c167cc87184dd062510b4c84d693a1892ee6a1ca/vendor/github.com/prometheus/common/model/metric.go#L504) is destructive - at least the `U__` prefix will disappear from the label name even if there are no Unicode symbols.

### Describe Your Changes

If the label is encoded according to the Prometheus UTF8 encoding scheme (https://github.com/prometheus/proposals/blob/main/proposals/0028-utf8.md), decode it before doing the search.

Every label value that starts with "U__" is considered to be UTF8-encoded, according to the spec.

Fixes #10446.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres to [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/victoriametrics/contributing/#pull-request-checklist).
- [x] My change adheres to [VictoriaMetrics development goals](https://docs.victoriametrics.com/victoriametrics/goals/).

### Checklist TODOs

- [x] Add the CHANGELOG line when the discussion is finished.

### CODE REVIEW

File: app/vmselect/prometheus/prometheus.go [hunk 1]
```diff
@@ -925,7 +933,8 @@ func QueryRangeHandler(qt *querytracer.Tracer, startTime time.Time, w http.Respo
 }
 
 func queryRangeHandler(qt *querytracer.Tracer, startTime time.Time, w http.ResponseWriter, query string,
-	start, end, step int64, r *http.Request, ct int64, etfs [][]storage.TagFilter) error {
+	start, end, step int64, r *http.Request, ct int64, etfs [][]storage.TagFilter,
```
Comment (f41gh7) [inline app/vmselect/prometheus/prometheus.go]: This change seems irrelevant, please revert it.

File: app/vmselect/prometheus/prometheus.go [hunk 2]
```diff
@@ -643,7 +652,6 @@ func LabelsHandler(qt *querytracer.Tracer, startTime time.Time, w http.ResponseW
 //
 // See https://prometheus.io/docs/prometheus/latest/querying/api/#querying-metric-metadata
 func MetadataHandler(qt *querytracer.Tracer, startTime time.Time, w http.ResponseWriter, r *http.Request) error {
-
```
Comment (f41gh7) [inline app/vmselect/prometheus/prometheus.go:647]: Same, there is no need for empty line

File: app/vmselect/prometheus/prometheus.go [hunk 3]
```diff
@@ -527,6 +528,14 @@ func LabelValuesHandler(qt *querytracer.Tracer, startTime time.Time, labelName s
 		return err
 	}
 	sq := storage.NewSearchQuery(cp.start, cp.end, cp.filterss, *maxLabelsAPISeries)
+
+	if strings.HasPrefix(labelName, "U__") {
+		// This label seems to be Unicode-encoded according to the Prometheus spec.
+		// See https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values
+		// Spec: https://github.com/prometheus/proposals/blob/main/proposals/0028-utf8.md
+		labelName = model.UnescapeName(labelName, model.ValueEncodingEscaping)
```
Comment (f41gh7) [inline app/vmselect/prometheus/prometheus.go]: It'd be great to have an integration test for this case at `apptests`.

File: app/vmselect/prometheus/prometheus.go (hunk 2 above)
Comment (utrack) [reply app/vmselect/prometheus/prometheus.go:647]: overzealous gofumpt, apols - fixed

File: app/vmselect/prometheus/prometheus.go (hunk 1 above)
Comment (utrack) [reply app/vmselect/prometheus/prometheus.go]: ditto, fixed

**Comment by utrack** [comment]
@f41gh7 ready for the review; test cases added

File: app/vmselect/prometheus/prometheus.go [hunk 4]
```diff
@@ -14,6 +14,7 @@ import (
 
 	"github.com/VictoriaMetrics/metrics"
 	"github.com/VictoriaMetrics/metricsql"
+	"github.com/prometheus/common/model"
```
Comment (f41gh7) [inline app/vmselect/prometheus/prometheus.go]: A single import increases binary size by 4MB, which is not acceptable for us.

I suggest to add a copy past for escaping function:

```diff
diff --git a/app/vmselect/prometheus/prometheus.go b/app/vmselect/prometheus/prometheus.go
index 22d59d7199..d21dc70c8f 100644
--- a/app/vmselect/prometheus/prometheus.go
+++ b/app/vmselect/prometheus/prometheus.go
@@ -11,10 +11,10 @@ import (
 	"sync"
 	"sync/atomic"
 	"time"
+	"unicode/utf8"
 
 	"github.com/VictoriaMetrics/metrics"
 	"github.com/VictoriaMetrics/metricsql"
-	"github.com/prometheus/common/model"
 	"github.com/valyala/fastjson/fastfloat"
 
 	"github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage"
@@ -533,7 +533,7 @@ func LabelValuesHandler(qt *querytracer.Tracer, startTime time.Time, labelName s
 		// This label seems to be Unicode-encoded according to the Prometheus spec.
 		// See https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values
 		// Spec: https://github.com/prometheus/proposals/blob/main/proposals/0028-utf8.md
-		labelName = model.UnescapeName(labelName, model.ValueEncodingEscaping)
+		labelName = unescapePrometheusLabelName(labelName)
 	}
 
 	labelValues, err := netstorage.LabelValues(qt, labelName, sq, limit, cp.deadline)
@@ -1345,3 +1345,70 @@ func calculateMaxUniqueTimeSeriesForResource(maxConcurrentRequests, remainingMem
 func GetMaxUniqueTimeSeries() int {
 	return maxUniqueTimeseriesValue
 }
+
+// copied from https://github.com/prometheus/common/blob/adea6285c1c7447fcb7bfdeb6abfc6eff893e0a7/model/metric.go#L483
+// it's not possible to use direct import due to increased binary size
+func unescapePrometheusLabelName(name string) string {
+	// lower function taken from strconv.atoi.
+	lower := func(c byte) byte {
+		return c | ('x' - 'X')
+	}
+	if len(name) == 0 {
+		return name
+	}
+	escapedName, found := strings.CutPrefix(name, "U__")
+	if !found {
+		return name
+	}
+
+	var unescaped strings.Builder
+TOP:
+	for i := 0; i < len(escapedName); i++ {
+		// All non-underscores are treated normally.
+		if escapedName[i] != '_' {
+			unescaped.WriteByte(escapedName[i])
+			continue
+		}
+		i++
+		if i >= len(escapedName) {
+			return name
+		}
+		// A double underscore is a single underscore.
+		if escapedName[i] == '_' {
+			unescaped.WriteByte('_')
+			continue
+		}
+		// We think we are in a UTF-8 code, process it.
+		var utf8Val uint
+		for j := 0; i < len(escapedName); j++ {
+			// This is too many characters for a utf8 value based on the MaxRune
+			// value of '\U0010FFFF'.
+			if j >= 6 {
+				return name
+			}
+			// Found a closing underscore, convert to a rune, check validity, and append.
+			if escapedName[i] == '_' {
+				utf8Rune := rune(utf8Val)
+				if !utf8.ValidRune(utf8Rune) {
+					return name
+				}
+				unescaped.WriteRune(utf8Rune)
+				continue TOP
+			}
+			r := lower(escapedName[i])
+			utf8Val *= 16
+			switch {
+			case r >= '0' && r <= '9':
+				utf8Val += uint(r) - '0'
+			case r >= 'a' && r <= 'f':
+				utf8Val += uint(r) - 'a' + 10
+			default:
+				return name
+			}
+			i++
+		}
+		// Didn't find closing underscore, invalid.
+		return name
+	}
+	return unescaped.String()
+}

```

File: apptest/tests/metricsql_test.go [hunk 5]
```diff
@@ -236,3 +240,42 @@ func testQueryRangeWithAtModifier(t *testing.T, sut apptest.PrometheusWriteQueri
...
+	cmpOptions := []cmp.Option{}
+
+	// encoded via prometheus model.EscapeName(string,model.ValueEncodingEscaping)
+	want := map[string][]string{
+		"__name__": {"labelvals"},
+		"U__kubernetes__something_2f_special_26__27__20_chars": {"漢©®€£"},
+		"U___33__1f44b_tf_306b__3061__306f_":                 {"漢©®€£"},
+	}
+	for labelName, expected := range want {
+		got := sut.PrometheusAPIV1LabelValues(t, labelName, `{__name__="labelvals"}`, apptest.QueryOpts{})
```
Comment (f41gh7) [inline apptest/tests/metricsql_test.go]: It's required to have fixed query time range for API request:

```diff
diff --git a/apptest/tests/metricsql_test.go b/apptest/tests/metricsql_test.go
index af5c62491c..e47ac19fed 100644
--- a/apptest/tests/metricsql_test.go
+++ b/apptest/tests/metricsql_test.go
@@ -246,6 +246,7 @@ func testQueryRangeWithAtModifier(t *testing.T, sut apptest.PrometheusWriteQueri
 // Spec: https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values
 func testLabelValuesWithUTFNames(t *testing.T, sut apptest.PrometheusWriteQuerier) {

+       timestamp := millis("2025-01-01T00:00:00Z")
        data := prompb.WriteRequest{
                Timeseries: []prompb.TimeSeries{
                        {
@@ -255,7 +256,7 @@ func testLabelValuesWithUTFNames(t *testing.T, sut apptest.PrometheusWriteQuerie
                                        {Name: "3👋tfにちは", Value: "漢©®€£"},
                                },
                                Samples: []prompb.Sample{
-                                       {Value: 1, Timestamp: millis("2026-02-17T00:01:00Z")},
+                                       {Value: 1, Timestamp: timestamp},
                                },
                        },
                },
@@ -270,12 +271,15 @@ func testLabelValuesWithUTFNames(t *testing.T, sut apptest.PrometheusWriteQuerie
        want := map[string][]string{
                "__name__": {"labelvals"},
                "U__kubernetes__something_2f_special_26__27__20_chars": {"漢©®€£"},
-               "U___33__1f44b_tf_306b__3061__306f_":                 {"漢©®€£"},
+               "U___33__1f44b_tf_306b__3061__306f_":                   {"漢©®€£"},
        }
        for labelName, expected := range want {
-               got := sut.PrometheusAPIV1LabelValues(t, labelName, `{__name__="labelvals"}`, apptest.QueryOpts{})
+               got := sut.PrometheusAPIV1LabelValues(t, labelName, `{__name__="labelvals"}`, apptest.QueryOpts{
+                       Start: fmt.Sprintf("%d", timestamp),
+                       End:   fmt.Sprintf("%d", timestamp),
+               })
                if diff := cmp.Diff(expected, got.Data, cmpOptions...); diff != "" {
                        t.Errorf("unexpected response (-want, +got):\n%s", diff)
                }
        }
-}
\ No newline at end of file
+}
```

**Comment by f41gh7** [comment]
Thanks for contribution!
