### PR TITLE
app/vlinsert/syslog: fixed parsing data, that contains allowed by a rfc5424 escaped characters

### LINKED ISSUE #8282: VictoriaLogs does not parse syslog messages with SD-PARAM values containing escaped characters
### Describe the bug

I setup VictoriaLogs for the first time to collect logs from a Synology NAS. On the Synology I am forwarding syslog messages to VictoriaLogs in IETF RFC 5424 format. 

Image

When I use the "Send test log" button, everything works. 

The following message is sent:

```
<14>1 2025-02-11T12:30:50+01:00 synology System - - [meta sequenceId="1"] Test message from Synology Syslog Client from (127.0.0.1)
```

And VictoriaLogs shows me:

```json
  {
    "_time": "2025-02-11T11:30:50Z",
    "_stream_id": "0000000000000000324f67748b863d80d4f889348ec4ea89",
    "_stream": "{app_name=\"System\",hostname=\"synology\",proc_id=\"-\"}",
    "_msg": "Test message from Synology Syslog Client from (127.0.0.1)",
    "app_name": "System",
    "facility": "1",
    "format": "rfc5424",
    "hostname": "synology",
    "meta.sequenceId": "1",
    "msg_id": "-",
    "priority": "14",
    "proc_id": "-",
    "severity": "6"
  }
```

All good for test, but then any real syslog message does not get parsed correctly and I get this instead:

```json
  {
    "_time": "2025-02-11T11:31:28Z",
    "_stream_id": "00000000000000000a84393b60f73921ad1aa2e348206217",
    "_stream": "{app_name=\"Connection\",hostname=\"synology\",proc_id=\"-\"}",
    "_msg": "missing _msg field; see https://docs.victoriametrics.com/victorialogs/keyconcepts/#message-field",
    "app_name": "Connection",
    "facility": "1",
    "format": "rfc5424",
    "hostname": "synology",
    "msg_id": "-",
    "priority": "14",
    "proc_id": "-",
    "severity": "6"
  }
```

The above is the result of the following syslog message captured on the wire:

```
<14>1 2025-02-11T12:31:28+01:00 synology Connection - - [synolog@6574 event_id="0x0001" synotype="Connection" username="synouser" luser="synouser" event="User [synouser\] from [192.168.0.10\] logged in successfully via [SSH\]." arg_1="synouser" arg_2="1027" arg_3="192.168.0.10" arg_4="SSH"][meta sequenceId="7"] \xef\xbb\xbfUser [synouser] from [192.168.0.10] logged in successfully via [SSH].
```

I debugged this and found out that this param is breaking parsing: 

```
event="User [synouser\] from [192.168.0.10\] logged in successfully via [SSH\]."
```

The problem is with the brackets `[]` in the string. I tried to escape both, escape none, but it cannot parse it. 

According to RFC5424 the PARAM-VALUE is an UTF-8 string with `"`, `\` and `]` escaped, which in my case indeed is escaped. Right now it seems to me that this is a parsing bug in VictoriaLogs, could you please check if this is the case?

```
      PARAM-VALUE     = UTF-8-STRING ; characters '"', '\' and
                                     ; ']' MUST be escaped.
```

I checked that the opening bracket alone works, so the problem is with the closing bracket. 

### To Reproduce

```
echo "<14>1 $(date -Iseconds) localhost Test - - [event=\"[test\\]\"] Test message" | nc -u $VLHOST $VLSYSLOGPORT
```

### Version

Docker image: `victoriametrics/victoria-logs:v1.9.1-victorialogs`
Docker image hash: `sha256:b5a3fc09508317bb33e96d5c4dc39614a73d28acda60e25a7e2fd4f804eeec71`

```
2025-02-11T11:10:59.182Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: victoria-logs-20250210-163129-tags-v1.9.1-victorialogs-0-g4600724985
```

### Logs

Nothing logged, no errors, no info. 

### Screenshots

N/A

### Used command-line flags

Docker compose:

```
  victorialogs:
    container_name: victorialogs
    image: victoriametrics/victoria-logs:v1.9.1-victorialogs
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 9428:9428
      - 127.0.0.1:29514:29514/udp
    volumes:
      - /volume1/docker/victorialogs/data:/vmdata
      - /volume1/docker/victorialogs/config:/vmconfig
    command: >-
      -syslog.listenAddr.udp=:29514
      -retentionPeriod=1y
      -storageDataPath=/vmdata
      -httpAuth.username=vmuser
      -httpAuth.password=file:///vmconfig/httpauth.key
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### Describe Your Changes

fixes #8282

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

File: lib/logstorage/syslog_parser.go [hunk 1]
```diff
@@ -281,7 +293,9 @@ func (p *SyslogParser) parseRFC5424SDLine(s string) (string, bool) {
 		return s, false
 	}
 
-	sdValue := strings.TrimSpace(s[:i])
+	fmt.Println(strings.TrimSpace(s[:i]))
```
Comment (jiekun) [inline lib/logstorage/syslog_parser.go:296]: I assume it's ready for review. Please remove debug codes L296 & L298

**Review by jiekun — CHANGES_REQUESTED** [review]

File: lib/logstorage/syslog_parser.go (hunk 1 above)
Comment (AndrewChubatiuk) [reply lib/logstorage/syslog_parser.go]: done

**Review by zekker6 — APPROVED** [review]

**Comment by jiekun** [comment]
Hello! Thanks for the fix. I'm checking the [cases in issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8282#issuecomment-2650726073), is it a valid case:
```go
f(`<14>1 2025-02-18T17:07:38+08:00 localhost Test - - [event="quote \"test\""] Test message`, time.UTC, `<todo>`)
```
I felt like getting incorrect `s` after https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a2bffd5f96745f27b66cabf3690d09c21bf804bd/lib/logstorage/syslog_parser.go#L240

Should we got `event="quote \"test\"` as `sdID` instead of `event="quote` (I'm getting this one now)?

But please ignore if the input is invalid at the first place.

**Comment by AndrewChubatiuk** [comment]
hey @jiekun 
as i understood from rfc5425, this case is not valid as sd-param should contains sd-id

```
f(`<14>1 2025-02-18T17:07:38+08:00 localhost Test - - [sdid event="quote \"test\""] Test message`, time.UTC, `<todo>`)
```

**Review by jiekun — APPROVED** [review]
LGTM. Thanks. Just FYI I tested the following case as well, which has multiple fields within `[` and `]`, and it works good:
```
	f(`<14>1 2025-02-18T11:37:42+02:00 localhost Test - - [test event="quote \"test\"" event2="quote2 \"test2\""] Test message`, time.UTC, `priority=14 facility=1 severity=6 format=rfc5424 timestamp=2025-02-18T11:37:42+02:00 hostname=localhost app_name=Test proc_id=- msg_id=- test.event="quote \"test\"" test.event2="quote2 \"test2\"" message="Test message"`)
```

**Review by f41gh7 — APPROVED** [review]
LGTM
