### PR TITLE
lib/promscrape/discovery/azure: remove API server from URL returned by azure

### LINKED ISSUE #3247: Issue with Single v.1.82.0 azure_sd_configs
**Describe the bug**

Single-node Victoriametrics is not able to get a list of VMs from subscription.
I'm using the ManagedIdentity authentication method and the VMs Identity has Reader role on subscription level.

It throws the error: 
404; expecting 200; response body: "{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}"

NOTE - it works when using recource_group parameter, but workaround of me scraping all resource groups this way is not suitable. 
NOTE2 - The subscriptions is for both dev & stage, currently am testing the victoriametrics in dev (it has no access to stage vm's due to firewall). Plan was to use relabel_configs to drop the stage vm's from the scrape
NOTE3 - It works fine on Prometheus, I'm currently testing VictoriaMetrics as a possible replacement., 

**To Reproduce**

1. Prepare YAML file with scrape config for victoriametrics to use
2. Grant VM on which victoriametrics is running Reader rights to the Azure Subscription
3. Run victoriametrics with -promscrape.config 
4. Get the following error:

Oct 13 12:22:17 dev-********* victoriametrics[18349]: 2022-10-13T12:22:17.634Z        error        VictoriaMetrics/lib/promscrape/config.go:1016        skipping azure_sd_config targets for job_name "azure_vms" because of error: cannot list virtual machines: cannot execute azure api request at https://management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/**********_STAGE/VMs/********: unexpected status code returned from "https://management.azure.comhttps//management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/***********_STAGE/VMs/*********": 404; expecting 200; response body: "{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}"

**Expected behavior**

Expecting the following log entry:
VictoriaMetrics/lib/promscrape/scraper.go:403        azure_sd_configs: added targets: 46, removed targets: 0; total targets: 46

**Logs**

Oct 13 12:22:17 dev-vic****** victoriametrics[18349]: 2022-10-13T12:22:17.634Z        error        VictoriaMetrics/lib/promscrape/config.go:1016        skipping azure_sd_config targets for job_name "azure_vms" because of error: cannot list virtual machines: cannot execute azure api request at https://management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/**********_STAGE/VMs/********: unexpected status code returned from "https://management.azure.comhttps//management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/***********_STAGE/VMs/*********": 404; expecting 200; response body: "{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}"

**Screenshots**

Scrape config
image

Turned on System Assigned Identity
image

Role Assignment
image

**Version**
victoria-metrics-20221007-004302-tags-v1.82.0-0-g832276064

**Used command-line flags**
/usr/local/bin/victoria-metrics-prod -storageDataPath=/data/victoria/ -selfScrapeInterval=30s -retentionPeriod=60 -maxConcurrentInserts=32 -search.maxUniqueTimeseries=900000 -promscrape.config=/data/scrape/prometheus.yml

### PR DESCRIPTION
**Pull request by zekker6**
Fixes #3247

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

File: lib/promscrape/discovery/azure/machine.go [hunk 1]
```diff
@@ -78,7 +80,8 @@ func visitAllAPIObjects(ac *apiConfig, apiURL string, cb func(data json.RawMessa
 				return err
 			}
 		}
-		nextLink = lar.NextLink
+		// Azure API returns nextLink with apiServer in it, so we need to remove it
```
Comment (f41gh7) [inline lib/promscrape/discovery/azure/machine.go:83]: I suggest to change semantic, rename nextLink for nextLinkURI, make for loop without condition and check nextLink at the end of the loop:
```go
               if lar.NextLink == "" {
			break
		}
		nextURL, err := url.Parse(lar.NextLink)
		if err != nil {
			return err
		}
		nextLinkURI = nextURL.RequestURI()
```

Replace look unreliable for me, since it may omit scheme or port at nextLink.

Comment (zekker6) [reply lib/promscrape/discovery/azure/machine.go]: Implemented this approach, thanks for suggestion!

**Review by f41gh7 — APPROVED** [review]
LGTM

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@zekker6 , thanks for the fix!
