### PR TITLE
vmalert: delete labels from rule results if they are specified with an empty string value

### LINKED ISSUE #10766: vmalert keeps source label when rule label is set to empty string
### Describe the bug

When an alerting rule contains a label override with an empty string, vmalert drops the empty override itself, but does not remove the same label if it is already present in the query result. It is inconsistent with Prometheus  behavior.

Example rule:
```
- alert: ContainerRestartedDueToOOMKill
  expr: (kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} and on(namespace, pod, container) (increase(kube_pod_container_status_restarts_total[10m]) > 0))
      * on(namespace, pod, uid) group_left(label_product)
    kube_pod_labels
  labels:
    priority: P4
    product: '{{ $labels.label_product }}'
    alert_topic: infra
    job: ""

```
Example query result labels before rule labels are applied:
`{container="data-flow-chart", job="kube-state-metrics", label_product="", reason="OOMKilled", uid="77c2b883-8d37-48c3-ae4d-ea63c5933dea",...}`

Example query result labels before rule labels are applied:
`ALERTS{alertname="ContainerRestartedDueToOOMKill", container="data-flow-chart", job="kube-state-metrics", priority="P4", reason="OOMKilled", uid="77c2b883-8d37-48c3-ae4d-ea63c5933dea",...}`

Expected behavior (no job label at all):
`ALERTS{alertname="ContainerRestartedDueToOOMKill", container="data-flow-chart", priority="P4", reason="OOMKilled", uid="77c2b883-8d37-48c3-ae4d-ea63c5933dea",...}`

The job label should be removed from the resulting alert series when the rule contains job: "", even if job is present in the datasource result.

### To Reproduce

1. Choose any metric with a non-empty `job` label in the query result.
2. Create an alerting rule for it with `job: ""` in `labels` section.
3. Check the resulting `ALERTS` series.

Current result:
`job` is still present.

Expected result:
`job` is removed.

### Version

v1.136.1-enterprise

### Logs

_No response_

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Haleygo**
fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/10766

### CODE REVIEW

File: app/vmalert/rule/recording.go [hunk 1]
```diff
@@ -293,9 +293,16 @@ func (rr *RecordingRule) toTimeSeries(m datasource.Metric) prompb.TimeSeries {
...
 	for k := range rr.Labels {
-		// do not add label with empty value, since it has no meaning.
-		// see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9984
+		// do not add label with empty value to the result, as it has no meaning:
+		// if the label already exists in the original query result, remove it to preserve compatibility with relabeling, see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/10766.
+		// otherwise, ignore the label, see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9984.
 		if rr.Labels[k] == "" {
+			for i := range m.Labels {
+				if m.Labels[i].Name == k {
+					m.Labels = append(m.Labels[:i], m.Labels[i+1:]...)
```
Comment (f41gh7) [inline app/vmalert/rule/recording.go]: WDYT of:
```
		m.Labels =  slices.DeleteFunc(m.Labels, func(label prompb.Label) bool {
			return label.Name == k
		})

```

File: app/vmalert/rule/recording.go [hunk 2]
```diff
@@ -293,9 +293,16 @@ func (rr *RecordingRule) toTimeSeries(m datasource.Metric) prompb.TimeSeries {
...
+					break
+				}
+			}
```
[the remark this answers is not in the document]
Comment (Haleygo) [reply app/vmalert/rule/recording.go]: The __name__ label should be forbidden as rule's label when parse rule config, added validation in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/10852/commits/1f0e71cecec82d507f053a54bbde39dd175ac902.

File: app/vmalert/rule/recording.go (hunk 1 above)
Comment (Haleygo) [reply app/vmalert/rule/recording.go]: Oh, just noticed we already have 
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0c05b0b15bfa27a1b392b732ef197994935795e3/app/vmalert/datasource/datasource.go#L86-L92

I'd prefer to reuse it and it's safe to break after find the first match.

**Review by f41gh7 — APPROVED** [review]
LGTM

File: app/vmalert/config/config.go [hunk 3]
```diff
@@ -222,6 +222,9 @@ func (r *Rule) Validate() error {
 	if r.Expr == "" {
 		return fmt.Errorf("expression can't be empty")
 	}
+	if r.Labels["__name__"] != "" {
```
Comment (f41gh7) [inline app/vmalert/config/config.go]: It looks like undocumented extra change. 

I'd expect the following check:

```
if _, ok := r.Labels["__name__"]; ok  {
   return fmt.Errorf("rule cannot modify label __name__")
}
```

Comment (Haleygo) [reply app/vmalert/config/config.go]: Applied change, it seems too minor for doc though, more like an extra safe check.

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by f41gh7** [comment]
Bugfix was back-ported into v1.122 and v1.136 LTS branches
