### PR TITLE
lib/backup/s3remote: fixed credsFilePath flag

### LINKED ISSUE #6353: vmbackup work at custom S3 get http 403
### Is your question request related to a specific component?

```bash
[root@vm prometheus]# vmbackup -storageDataPath=/prometheus/victoria-metrics-data -snapshot.createURL=http://localhost:8428/snapshot/create -dst=s3://victoriametrics-backup/tcsgp -customS3Endpoint=https://s3-api.example-minio.com -credsFilePath=/prometheus/minioCredentials
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmbackup-20240425-145523-tags-v1.101.0-0-g5334f0c2c
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/logger/flag.go:20	  -credsFilePath="/prometheus/minioCredentials"
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/logger/flag.go:20	  -customS3Endpoint="https://s3-api.example-minio.com"
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/logger/flag.go:20	  -dst="s3://victoriametrics-backup/tcsgp"
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/logger/flag.go:20	  -snapshot.createURL="secret"
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageDataPath="/prometheus/victoria-metrics-data"
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/app/vmbackup/main.go:67	Snapshot create url http://localhost:8428/snapshot/create
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/app/vmbackup/main.go:78	Snapshot delete url http://localhost:8428/snapshot/delete
2024-05-27T10:17:22.125+0200	info	VictoriaMetrics/lib/snapshot/snapshot.go:32	Creating snapshot
2024-05-27T10:17:22.232+0200	info	VictoriaMetrics/lib/snapshot/snapshot.go:64	Snapshot 20240527081722-17D33C03CDB6965D created
2024-05-27T10:17:22.232+0200	info	VictoriaMetrics/lib/httpserver/httpserver.go:119	starting server at http://127.0.0.1:8420/
2024-05-27T10:17:22.232+0200	info	VictoriaMetrics/lib/httpserver/httpserver.go:120	pprof handlers are exposed at http://127.0.0.1:8420/debug/pprof/
2024-05-27T10:17:22.232+0200	info	VictoriaMetrics/lib/backup/s3remote/s3.go:118	Using provided custom S3 endpoint: "https://s3-api.example-minio.com"
2024-05-27T10:17:25.659+0200	info	VictoriaMetrics/lib/snapshot/snapshot.go:75	Deleting snapshot 20240527081722-17D33C03CDB6965D
2024-05-27T10:17:25.668+0200	info	VictoriaMetrics/lib/snapshot/snapshot.go:108	Snapshot 20240527081722-17D33C03CDB6965D deleted
2024-05-27T10:17:25.668+0200	fatal	VictoriaMetrics/app/vmbackup/main.go:104	cannot create backup: cannot delete `backup complete` file at S3{bucket: "victoriametrics-backup", dir: "tcsgp/"}: cannot open "backup_complete.ignore" at S3{bucket: "victoriametrics-backup", dir: "tcsgp/"} (remote path "tcsgp/backup_complete.ignore"): operation error S3: GetObject, https response error StatusCode: 403, RequestID: 17D34A8B64A8FA05, HostID: 28314b1bfe2eff11603ecd4e0aa18484bd21af7e399acd2054bf1284c18135a2, api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method**

### Describe the question in detail

I can not use `vmbackup` to backup my data to minio-S3, but when I test the AK/SK in `minioCredentials` in python-script with minio-client, It can work to my custom S3 Bucket

```text
[default]
aws_access_key_id=xxxxxxxxxxxxx
aws_secret_access_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### Describe Your Changes

properly use credsFilePath flag value
fixes #6353

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

File: lib/backup/s3remote/s3.go [hunk 1]
```diff
@@ -99,9 +99,14 @@ func (fs *FS) Init() error {
...
 
-	if len(fs.CredsFilePath) > 0 {
+	if len(fs.ConfigFilePath) > 0 {
 		configOpts = append(configOpts, config.WithSharedConfigFiles([]string{
 			fs.ConfigFilePath,
+		}))
+	}
+
+	if len(fs.CredsFilePath) > 0 {
+		configOpts = append(configOpts, config.WithSharedCredentialsFiles([]string{
```
Comment (zekker6) [inline lib/backup/s3remote/s3.go:109]: Based on AWS SDK code here - https://github.com/VictoriaMetrics/VictoriaMetrics/blob/b12864f9055afa4abd5b8c4f2fe775b55e24402d/vendor/github.com/aws/aws-sdk-go-v2/config/load_options.go#L386-L391
It looks like it is required to construct an array of files an pass an array only once as otherwise it will override the value. 
Could you please update the PR to address this?

**Review by zekker6 — CHANGES_REQUESTED** [review]

File: lib/backup/s3remote/s3.go (hunk 1 above)
Comment (AndrewChubatiuk) [reply lib/backup/s3remote/s3.go:109]: WithSharedConfigFiles is executed only once

Comment (zekker6) [reply lib/backup/s3remote/s3.go:109]: Ah, sorry, my bad!

**Review by zekker6 — APPROVED** [review]
LGTM

**Review by hagen1778 — APPROVED** [review]
Thanks!
