### PR TITLE
vmui: fix trailing slash in serverURL

### LINKED ISSUE #5203: vmui: strip slashes from datasource address
### Describe the bug

I've tried to [Explore Cardinality](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality?date=2023-10-19) of the [Prometheus instance](https://demo.promlabs.com/) and got the error: failed to fetch.

From the error msg it wasn't clear what is wrong. So after some adjustments I made it work by removing `/` 
from the `https://demo.promlabs.com/`. Would be nice if vmui or VM could do it automatically.

### To Reproduce

Go to https://play.victoriametrics.com and try pointing it to https://demo.promlabs.com/

### Version

v1.94

cc @Loori-R

### PR DESCRIPTION
**Pull request by Loori-R**
- Added a function to automatically remove `/` at the end of the `serverURL` variable to ensure correct URL formation.
- Fixes #5203

### CODE REVIEW

File: app/vmui/packages/vmui/src/utils/url.ts [hunk 1]
```diff
@@ -8,4 +8,6 @@ export const isValidHttpUrl = (str: string): boolean => {
   }
 
   return url.protocol === "http:" || url.protocol === "https:";
-};
\ No newline at end of file
+};
+
+export const removeTrailingSlash = (url: string) => url.endsWith("/") ? url.slice(0, -1) : url;
```
Comment (dmitryk-dk) [inline app/vmui/packages/vmui/src/utils/url.ts:13]: maybe below approach would be better in this case

```javascript
url.replace(/\/$/, "");
```

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , thanks for the fix!
